package com.efrei.entities;
import java.util.List;

import javax.persistence.Column;




import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Data 
@Getter @Setter 
public class WallTypes {
	private Integer Id;
	private String Keynote;
	private String Model;
	private String Manufacturer;
	private String TypeComments;
	private String URL;
	private String Description;
	private String OmniClassNumber;
	private String AssemblyCode;
	private String FamilyName;
	private String TypeName;
	private String TypeMark;
	private Float Cost;
	private String FireRating;
	private Float Width;
	private String Region_Europe;
	private String Region_Middle_East;
	private String Region_North_America;
	private String Region_Oceania;
	private String Region_South_America;
	private String Product_SKU;
	private String Technical_description;
	private String Uniclass_1_4_Code;
	private String Uniclass_1_4_Description;
	private String Uniclass_2015_Code;
	private String Uniclass_2015_Name;
	private String Uniclass_2_0_Code;
	private String Uniclass_2_0_Description;
	private String UNSPSC_Code;
	private Float Weight_Net_Kg;
	private Float Nominal_width;
	private String Author;
	private String BIMObjectName;
	private String ManufacturerName;
	private String ManufacturerURL;
	private String ProductInformation;
	private String Revision;
	private String Uniclass2;
	private String Version;
	private String AcousticRating;
	private Integer Combustible;
	private Integer IsExternal;
	private String Reference;
	private String SurfaceSpreadOfFlame;
	private String IfcExportAs;
	private String IfcExportType;
	private String AccessibilityPerformance;
	private String AssetType;
	private String Category;
	private String CodePerformance;
	private String Color;
	private String Constituents;
	private String DurationUnit;
	private String ExpectedLife;
	private String Features;
	private String Finish;
	private String Grade;
	private String Material;
	private String ModelNumber;
	private String ModelReference;
	private String Name;
	private Float NominalHeight;
	private Float NominalLength;
	private Float NominalWidth;
	private String ReplacementCost;
	private String Shape;
	private String Size;
	private String SustainabilityPerformance;
	private String WarrantyDescription;
	private String WarrantyDurationLabor;
	private String WarrantyDurationParts;
	private String WarrantyDurationUnit;
	private String WarrantyGuarantorLabor;
	private String WarrantyGuarantorParts;
	private String FlammibilityRating;
	private String FragilityRating;
	private String CladdingType;
	private String ApplicationOptions;
	private String SpanningDirection;
	private String ExternalSkinThicknessAndMaterial;
	private String ExternalProfileReference;
	private String ExternalProfileCrownWidth;
	private String ExternalProfileDepth;
	private String ExternalProfilePitch;
	private String ExternalSkinFinish;
	private String ExternalColourOptions;
	private String CoreInsulation;
	private String InternalLinerSkinThicknessAndMaterial;
	private String InternalLinerFinishOptions;
	private String InternalColourOptions;
	private String PanelThickness;
	private String LengthOptions;
	private String CoverWidthManufacturingTolerance;
	private String ThicknessManufacturingTolerance;
	private String LengthManufacturingTolerance;
	private String CutBacks;
	private String EndSquareManufacturingTolerance;
	private String FireResistanceOptions;
	private String PanelEndJoints;
	private String PanelEndLapArrangement;
	private String PrimaryFasteners;
	private String PanelJoints;
	private String PanelSideLapArrangement;
	private String CornerPanels;
	private String Curvature;
	private String IntegralAccessories;
	private String Guarantees;
	private String SpecialFeatures;
	private String ThermalTransmittance;
	private String TotalThickness;
	private String Product_data_url;
	private String BIMobject_category;
	private String COBIe_Type_Category;
	private String Design_country;
	private String EAN_code;
	private Integer Edition_number;
	private Float Nominal_height;
	private String IFC_Classification;
	private String Installation_instructions;
	private String Youtube_clip;
	private String Manufacturer_country;
	private String Manufacturer_name;
	private String Material_main;
	private String Material_secondary;
	private String OmniClass_Code;
	private String OmniClass_Description;
	private String Product_certification;
	private String Product_family;
	private String Product_group;
	private String Product_Guid;
	private String Product_name;
	private String Date_of_publishing;
	private String QR_code;
	private String Region_Africa;
	private String Region_Antarctica;
	private String Region_Asia;
}
